### ISSUE TITLE
Make sure package database exists before running `cabal install`

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell-tinc/tinc#15]
If we run `tinc` in `$HOME` without `.cabal` or with freshly created one, the package index won't exist at all and the test-suite will fail with (here `HOME=/tmp`):

```
Test suite acceptance: RUNNING...
Config file path source is default config file.
Config file /tmp/nix-build-tinc-0.1.0.drv-0/.cabal/config not found.
Writing default configuration to /tmp/nix-build-tinc-0.1.0.drv-0/.cabal/config
Writing a default package environment file to
/tmp/tinc-test-cache/tinc-setenv/cabal.sandbox.config
Creating a new sandbox at /tmp/tinc-test-cache/tinc-setenv/.cabal-sandbox
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
cabal: There is no package named 'setenv'.
You may need to run 'cabal update' to get the latest list of available
packages.
```

As running `--update` would probably take too long, it's probably enough to just check if any index exists and only run it if it does not.

**Comment by soenkehahn** [comment]
This seems to be a very nix-specific problem. Wouldn't it be easiest to just disable the test-suite in nix?

**Comment by Fuuzetsu** [comment]
>This seems to be a very nix-specific problem.

Does it? I don't think setting `HOME` to somewhere that's not the user's main profile is nix-specific only… It seems strange to rely on user's environment to be already set up in such and such way for the tests to pass…

>Wouldn't it be easiest to just disable the test-suite in nix?

Well, it's always better to have tests run and pass if possible rather than just disabling them. But if the fix is hard or not doable for whatever reason then that's what will happen.

**Comment by sol** [comment]
I think I agree with what @soenkehahn suggested, at least for now.

@Fuuzetsu did you try to use tinc with nix GHC btw?

**Comment by Fuuzetsu** [comment]
>I think I agree with what @soenkehahn suggested, at least for now.

Feel free to close then

>@Fuuzetsu did you try to use tinc with nix GHC btw?

It should work no different than regular GHC as long as everything is kept in cabal, at least for now. In the future there may be two GHCs, one that ignores .ghc and other cabal stuff on the system and one that does not. But I have not tried, I only got as far as trying to run the test-suite to see if I could do some hacking and gave up there. At least for me personally, tinc is not too high up there in priorities as I just use nix for caching.

But yeah, in principle it should work like on any other distro/package manager as long as one consistently uses cabal.
